from pathlib import Path

SRC_DIRECTORY = Path(__file__).parent
PROJECT_ROOT = SRC_DIRECTORY.parent
DATASET_RATINGS_PATH = PROJECT_ROOT / "datasets" / "ratings.csv"
DATASET_MOVIES_PATH = PROJECT_ROOT / "datasets" / "movies.csv"
RATINGS_USER_ID_COLUMN = "userId"
RATINGS_ITEM_ID_COLUMN = "movieId"
RATINGS_VALUE_COLUMN = "rating"
OUTPUT_DIRECTORY = PROJECT_ROOT / "output"
TRAINED_MODEL_PATH = OUTPUT_DIRECTORY / "trained_model.pkl"
TRAIN_RATINGS_PATH = OUTPUT_DIRECTORY / "train_ratings.csv"
TEST_RATINGS_PATH = OUTPUT_DIRECTORY / "test_ratings.csv"
LATENT_RANK = 10
REGULARIZATION_LAMBDA = 10.0
ALS_ITERATION_COUNT = 40
TEST_FRACTION = 0.2
RANDOM_SEED = 42
TOP_RECOMMENDATION_COUNT = 10
DEMO_USER_INDEX = 0
PLOT_EXAMPLE_COUNT = 8
